---
# tasks file for squid
- name: install squid
  package:
    name: "{{ squid_packages }}"
    state: present
  register: squid_install_squid
  until: squid_install_squid is succeeded
  retries: 3

- name: configure squid
  template:
    src: "{{ squid_config_file }}.j2"
    dest: "{{ squid_config_directory }}/{{ squid_config_file }}"
  notify:
    - test squid configuration
    - reload squid

- name: create group
  group:
    name: "{{ squid_group }}"
    system: yes
    state: present
  when: ansible_facts['os_family'] != "Debian"

- name: create user
  user:
    name: "{{ squid_user }}"
    group: "{{ squid_group }}"
    create_home: no
    state: present
    home: /var/spool/squid
    shell: /sbin/nologin
    system: yes
  when: ansible_facts['os_family'] != "Debian"

- name: create cache directory
  file:
    path: /var/spool/squid
    state: directory
    owner: "{{ squid_user }}"
    group: "{{ squid_group }}"
  notify:
    - test squid configuration
    - restart squid

- name: flush_handlers
  meta: flush_handlers

- name: start and enable squid
  service:
    name: "{{ squid_service }}"
    state: started
    enabled: yes
