---
# tasks file for squid
- name: test veriables and environment
  assert:
    that:
      - squid_package_state is defined
      - squid_package_state == "present" or
        squid_package_state == "latest" or
        squid_package_state == "absent"
      - squid_ignore_docker is defined
      - squid_ignore_docker or
        not squid_ignore_docker
      - squid_port is defined
      - squid_port >= 1
      - squid_port <= 65536
      - squid_cache_dir is defined

- name: install requirements
  package:
    name: "{{ squid_requirements }}"
    state: "{{ squid_package_state }}"
  when:
    - squid_requirements is defined

  register: squid_install_requirements
  until: squid_install_requirements is succeeded
  retries: 3

- name: install squid
  package:
    name: "{{ squid_packages }}"
    state: "{{ squid_package_state }}"
  register: squid_install_squid
  until: squid_install_squid is succeeded
  retries: 3

- name: configure squid
  template:
    src: "{{ squid_config_file }}.j2"
    dest: "{{ squid_config_directory }}/{{ squid_config_file }}"
  notify:
    - test squid configuration
    - restart squid

- name: create group
  group:
    name: "{{ squid_group }}"
    system: yes
    state: present

- name: create user
  user:
    name: "{{ squid_user }}"
    group: "{{ squid_group }}"
    create_home: no
    state: present
    home: /var/spool/squid
    shell: /sbin/nologin
    system: yes

- name: flush_handlers
  meta: flush_handlers

- name: start and enable squid
  service:
    name: "{{ squid_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker" or squid_ignore_docker
