---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: molecule
        uses: robertdebock/molecule-action@1.1.3
        with:
          entrypoint: /usr/local/bin/molecule
          args: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - amazonlinux"
            tag="1"
          - amazonlinux"
            tag="latest"
          - alpine"
            tag="master"
          - alpine"
            tag="edge"
          - debian"
            tag="latest"
          - debian"
            tag="unstable"
          - centos"
            tag="7"
          - centos"
            tag="8"
          - fedora"
            tag="30"
          - fedora"
            tag="latest"
          - fedora"
            tag="rawhide"
          - opensuse"
            tag="latest"
          - ubuntu"
            tag="latest"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: robertdebock/molecule-action@1.1.3
        with:
          image: ${{ matrix.image }}
          tag: ${{ matrix.tag }}
          options: "--parallel all"
